### ISSUE TITLE
Returns black image

### ISSUE THREAD

**Issue by cfjedimaster** [yahoo/gifshot#10]
I'm trying to test this under Cordova using video from the device camera. It runs successfully, but when I set the src to an image in the DOM, I just get a black square.

**Comment by gfranko** [comment]
We believe that we've fixed the black frame issue.  Let us know if you are still running into issues.

**Comment by cfjedimaster** [comment]
Looks good so far. Thanks.

On Wed, Aug 26, 2015 at 5:43 PM, Greg Franko <notifications@github.com>
wrote:

> We believe that we've fixed the black frame issue. Let us know if you are
> still running into issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yahoo/gifshot/issues/10#issuecomment-134838553>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden
