### ISSUE TITLE
How to use gifShot as a react component

### ISSUE THREAD

**Issue by git-ankur-shukla** [yahoo/gifshot#107]
Hey, gifShot seems to be an amazing library. Some help on how to use it as a **react component** would be really appreciated. Some variations to the callback function may be?

**Comment by Benjaki2** [comment]
Gifshot doesn't really render anything to the dom on it's own so you should be able to use it with react as is.
```
createGif() {
  var images = this.props.imageArray;
  gifshot.createGIF({
    'images': images
  },function(obj) {
    // do something with the obj depending on you're managing state
  });
}
render() {
  return (
   <Button onClick={this.createGif.bind(this)} />
  );
}

**Comment by daas-ankur-shukla** [comment]
@Benjaki2 thanks for the reply. i was able to do it similar to what u mentioned. :)

**Comment by gfranko** [comment]
Thanks for answering @Benjaki2 👍

**Comment by DheerajMahra** [comment]
I implemented this and I got an error - gifshot is not defined. But, I have linked the gifshot.js library in my index.html (public/index.html). Please help.

**Comment by DheerajMahra** [comment]
@Benjaki2 Hello, I implemented this in my react component and it says gifshot not defined. I found that gifshot is a property of window object. But, If I say window.gifshot it executes imediately. I want to run gifshot in componentDidMount.
