### ISSUE TITLE
question on video option

### ISSUE THREAD

**Issue by ttback** [yahoo/gifshot#11]
Is the video option 'example.mp4' supposed to be a url to the mp4 file? or is it possible to reference a <video> tag on the page? I am trying to convert part of a video to gif, with (start, duration) as input, is it possible with gifshot?

**Comment by gfranko** [comment]
@rockinghelvetica I've never used that before, but it sounds like it would work

**Comment by whydna** [comment]
@gfranko  you mentioned about supporting specific points in video - any update on that?
