### ISSUE TITLE
Option to overlay a logo/image

### ISSUE THREAD

**Issue by Benjaki2** [yahoo/gifshot#110]
Overlaying a GIF with your logo or some funny image to make the GIF even more funny. 

Example from a nasa-gibs forked version:
![nasa-worldview-2017-09-05-to-2017-09-13](https://user-images.githubusercontent.com/3605988/38333157-caf797f4-3825-11e8-9cef-a27f451d7d6e.gif)

Would you all accept a PR for this?

**Comment by gfranko** [comment]
Definitely, would love to have this "watermarking" feature added!
