### ISSUE TITLE
Support array of Base64 images, and array of text for each image

### ISSUE THREAD

**Issue by jasonrojas** [yahoo/gifshot#2]
Any chance we can get support for:

```
gifshot.createGIF({
    'images': ["data:image/jpeg;base64,/9...", "data:image/jpeg;base64,/9"],
    'text': ["Text1", "Text2"]
}, function (obj) {
    if(!obj.error) {
        var image = obj.image,
        animatedImage = document.createElement('img');
        animatedImage.src = image;
        document.body.appendChild(animatedImage);
    }
});
```

etc?

**Comment by gfranko** [comment]
Will look into fixing this in the next release

**Comment by adamb0mb** [comment]
Is there a "resurrected from the dead" emoji? That could be useful here :-). Glad to see movement from y'all again!

**Comment by gfranko** [comment]
@adamb0mb Just took a little bit of a break from open source haha

**Comment by biplabmalakar** [comment]
I am not using camera stream or any media from browser.  I am only passing array of image, but still its giving error regarding 'getUserMedia permission'. How can i fixed this problem.

**Comment by themre** [comment]
hi, has anyone started doing PR for this? perhaps I could take a look. most important is the ability to pass image blob and text to individual frame.
