### ISSUE TITLE
'Uint32Array' is undefined -- IE9

### ISSUE THREAD

**Issue by adamb0mb** [yahoo/gifshot#22]
```
'Uint32Array' is undefined
```
We got an error report this morning, and were able to repro it this afternoon (via BrowserStack). This seems to be an IE9 issue -- we're not seeing it on IE10 or IE11, or other modern browsers.

![screen shot 2014-10-14 at 2 01 17 pm](https://cloud.githubusercontent.com/assets/372235/4636724/4e869954-53e5-11e4-9292-bac0fb8cb287.png)

**Comment by gfranko** [comment]
We have fixed this in the **0.2.0** release.  Please let us know if you are still having issues.

**Comment by adamb0mb** [comment]
@gfranko I quit working on the team that was using your library... and I think they stripped support out. So, I can't test anymore :-(
