### ISSUE TITLE
NPM and/or browserify support?

### ISSUE THREAD

**Issue by nelix** [yahoo/gifshot#23]

**Comment by flavioribeiro** [comment]
hi @nelix, any plans to publish it?

**Comment by nelix** [comment]
@flavioribeiro no idea, this is not my library.
@gfranko I build it using webpack, works just fine. Save me all the extra npm install time and npm prune drama by getting this into npm?

**Comment by gfranko** [comment]
Just added Gifshot to [npm](https://www.npmjs.com/package/gifshot)

**Comment by nelix** [comment]
Thanks a lot @gfranko
