### ISSUE TITLE
When using the images option, the image sequence can be wrong

### ISSUE THREAD

**Issue by snorpey** [yahoo/gifshot#25]
I'm using a sequence of PNG images to create a gif. Some of the PNGs have a bigger file size than others and are all > 100KB.

    var files = ['file-01.png', 'file-02.png', 'file-xx.png'];
    gifshot.createGIF( { images: files } );

I added a [jsfiddle](http://jsfiddle.net/pq229a1q/1/) with the code I'm using.

Gifshot seems to add the images in the order of loading instead of the order of the ``gifshotOptions.images`` array. This can yield unexpected results, especially if the source files are large or if there's a lot of variation in the file sizes:

expected result:
![gifshot-correct-order](https://cloud.githubusercontent.com/assets/166433/5308380/5d07a9c4-7c16-11e4-963f-cd9752614702.gif)

actual result:
![gifshot-wrong-order](https://cloud.githubusercontent.com/assets/166433/5308381/5d180c24-7c16-11e4-9ea4-d975722de7b6.gif)

**Comment by gfranko** [comment]
Dupe
