### ISSUE TITLE
How to use GifShot with PHP and MYSQL

### ISSUE THREAD

**Issue by Mustafaoeztuerk** [yahoo/gifshot#27]
Hello. First of all congratulations to the successful script.
I'm doing a social network planning and i want to allow user create animation gif. I am a little beating on JavaScript. So there's something I do not understand. How can i upload an image from my user upload folder using PHP and MYSQL? 

You can explain to me about it?

**Comment by gfranko** [comment]
Gifshot outputs a base64 string, which allows you to pass it server-side, decode the image, and save it.  Check out this [stackoverflow](http://stackoverflow.com/questions/11511511/how-to-save-a-png-image-server-side-from-a-base64-data-string) article.

**Comment by Mustafaoeztuerk** [comment]
How can i call gifshot.js with AJAX. The developer tools everytime showing This line:

https://github.com/yahoo/gifshot/blob/master/demo/js/dependencies/gifshot.js#L1103

I need to call that function ?  This is my question from stackoverflow: 

http://stackoverflow.com/questions/28176243/imagecreatefromgif-from-base64-encoded-animated-gif-in-post

**Comment by gfranko** [comment]
Have you looked at the [demo](https://yahoo.github.io/gifshot/demo.html) page, which shows you the code that you need?

**Comment by Mustafaoeztuerk** [comment]
So everything is ok in GifShot plugin. Allow me to explain in the following.

A user creates gif animation this website is a social networking site and the user want to show a friends this animation gif. I am trying to do it with ajax. Create gif button and first ajax created base64 second ajax change base64 name like to uploads/12345678.gif . 

gifshot.js created base64 from this line:

https://github.com/yahoo/gifshot/blob/master/demo/js/dependencies/gifshot.js#L1103
My question is the how can i call that function with my AJAX. 

Note: I still looked at DEMO page . When created an gif then SAVE GIF button will come then clicked to download gif. I don't want it. I want to post a generated animation.

**Comment by Mustafaoeztuerk** [comment]
I fixed the problem thanks
