### ISSUE TITLE
When using images option, creation of gif doesn't always use all images

### ISSUE THREAD

**Issue by nityaoberoi** [yahoo/gifshot#31]
This is specifically a Safari and Firefox bug. In chrome this works perfectly.

I'm generating 3 images using the webcam and loading it as an array into the `gifshot.createGif` method. 
Sample code:
```
ImageBuilder.prototype.createGif = function(options, callback) {
    var self = this;
    gifshot.createGIF({
      images: self._imageArray, // array of 3 images with data urls
      gifWidth: options.imageWidth,
      gifHeight: options.imageHeight,
      interval: 0.4
    },
      function(obj) {
        if(!obj.error) {
          self._image.src = obj.image;
        } else {
          self.setError(obj.errorMsg);
        }
        if(callback) callback();
    });
  };
```

However, my resulting Gif about 90% of the time has only the first two images and the Gif Animation isn't able to capture the image drawn onto the third canvas. I don't face the problem however when I add a debugger and use it to navigate through the code as it seems like it gives the canvas some time to actually draw the image.

Working with your library on a time critical project so any solutions or work arounds for this soon, would be much appreciated!

**Comment by gfranko** [comment]
Can you re-test on version **0.2.0**?

**Comment by gfranko** [comment]
Any sequence order bugs for the **images** option should be fixed now.  Let me know if you run into any more issues!
