### ISSUE TITLE
How does the interval option works?

### ISSUE THREAD

**Issue by Billybobbonnet** [yahoo/gifshot#37]
Hello,

First, this is a great library, thanks for making it.

I want to generate a gif thumbnail out of my html5 mp4 video. My original plan was to do something like that:
```javascript
gifshot.createGIF({ 
      'video': [mediaData.raw],
      'interval': video.duration()/11
    },function(obj) {
      if(!obj.error) {
        var image = obj.image,
        animatedImage = document.createElement('img');
        animatedImage.src = image;
        document.body.appendChild(animatedImage);
      }
 });
````

The doc say that about `interval`:

> The amount of time (in seconds) to wait between each frame capture

And it seems to literally wait. Am I right? 

Now if I want to make a 10 image gif thumbnail for my video with one image every `video.duration()/11`, how should I proceed?

I was wondering if it is necessary to make it "manually', meaning using the `image: myArrayOfImages` option. I would display a loader on client, manually jump at each `video.duration()/11` interval and take a snapshot. Then I would push it in my array that will be used in the `image: myArrayOfImages` option. Would that be the way to go?

Thanks!

---
Edit: following @rockinghelvetica suggestion about Media Fragments API in https://github.com/yahoo/gifshot/issues/11, I tried that:
```javascript
      var videoSteps = [];
      var videoStepDuration = Math.round(this.duration()/11);
      console.log(videoStepDuration);
      for (i = 0; i < 10; i++) {
          videoSteps[i]= url + "?t=" + videoStepDuration*i;
      }
      var frameTime = 1 / 15; // assume 15 fps, no need for too small ips
      if (!mediaData.thumbnail){
        gifshot.createGIF({ //!\ DEBT to be changed once video are encoded
          'video': videoSteps
        },function(obj) {
          if(!obj.error) {
            var image = obj.image,
            animatedImage = document.createElement('img');
            animatedImage.src = image;
            document.body.appendChild(animatedImage);
          }
        });
 ``` 

But it only returns a gif coming from the first video

**Comment by gfranko** [comment]
The `interval` option will wait `x` amount of seconds before it tries to draw the video to the canvas and add that image as a frame.  This should create the gif that you are looking for.

I haven't personally tried the Media Fragments API unfortunately, so I can't be much help here.
