### ISSUE TITLE
Support For Converting Existing Video On Android?

### ISSUE THREAD

**Issue by nraboy** [yahoo/gifshot#39]
Hi,

I've been playing around with this library and it is pretty awesome.  However on Android, it doesn't seem to convert existing video to GIF format.  It works fine when piping in several existing images, but it doesn't do anything when it comes to video.

Nothing shows up in my logs.  It never seems to enter the callback.  No error, nothing.

Is this a known issue when it comes to video for Android?  The video format I'm using is MP4 and I'm using the latest Chromium Webview with Android L.  The videos are 5 seconds or less.

Please let me know.

Thanks,

**Comment by gfranko** [comment]
Thank you for reporting this.  I'll take a look and see why this is happening (it's happening on the demo gifshot demo page as well).

**Comment by nraboy** [comment]
Thanks, please report back with whatever you find :-)

**Comment by nraboy** [comment]
Any updates on this?

**Comment by shmuel-krakower** [comment]
I've spent 5 hours last night trying different options until I figured there's an open bug :/
Other than that - cool library! Thanks for creating it.

**Comment by caglarakturk** [comment]
I faced this bug, too.. I will be waiting an update or a reply

Please reply a comment

And of course thank you for this library.

**Comment by snowbreeze** [comment]
Facing the same issue. Images are working but video is not.

**Comment by Haeresis** [comment]
Same issue for me. I checked that today. With http video on same server or directly updated from Android device. It's ok for image, but not for video. Video are correctly imported in browser from `<input type="file">` with a `FileReader` object and setted in a `<video>` tag. But after that, via `URL.createObjectURL(file)` nothing happen on Android.

**Comment by snowbreeze** [comment]
Thats correct

**Comment by caglarakturk** [comment]
I checked js library then I found an exception while executing GetImageData function. I tried some alternatives but i havent solved yet

**Comment by khoimm92** [comment]
Hi, any update?

**Comment by gfranko** [comment]
The existing video demo on the site works on my Galaxy S5. Closing this for now.
