### ISSUE TITLE
Transparency?

### ISSUE THREAD

**Issue by bevacqua** [yahoo/gifshot#40]
Hey, I'm using this to create an animated gif out of SVG data uris. One issue I have is wrt transparency. Transparency gets rendered in black. Any workarounds or point me to where I can fix this?

**Comment by gfranko** [comment]
Could you set up a test page for me to look at?  Would gladly help debug.

**Comment by bevacqua** [comment]
Sure. http://codepen.io/bevacqua/pen/JYKOQL

**Comment by bevacqua** [comment]
All `vectorcam` does is take snapshots of the SVG as data uris and pass those to `gifshot`.

**Comment by bevacqua** [comment]
See: https://github.com/bevacqua/vectorcam/blob/master/vectorcam.js#L57

**Comment by gfranko** [comment]
Closing this for now, but you can try the latest gifshot version that we just released
