### ISSUE TITLE
Passing an array of Base64 dataurls doesn't seem to work on Firefox

### ISSUE THREAD

**Issue by calipoop** [yahoo/gifshot#41]
Gifshot successfully creates an animated GIF in Chrome & IE10 with an array of Base64 images.  But on Firefox it gets hung up, and creates what looks to be all frames as dataurls appended to the body, like this:

```
<img style="position: fixed; opacity: 0;" src="data:image/png;base64,iVBORw0KGg..." crossorigin="Anonymous">
```

See also this post by another user which suggests the same problem:
http://stackoverflow.com/q/29755732/2434324

**Comment by gfranko** [comment]
Closing this for now, but in the future please give us a code example to look at/test
