### ISSUE TITLE
Video from Dropbox gives a blank GIF

### ISSUE THREAD

**Issue by vinayvinay1** [yahoo/gifshot#42]
Hi,

Video added from dropbox gives a blank GIF. Is it any issue in the gifshot or should I build extra code to be able to add videos from dropbox ?

**Comment by marines** [comment]
I think it's due to cross-origin restrictions of Dropbox.

**Comment by gfranko** [comment]
We are accepting blog urls in the `video` option in the new release, which should be out shortly
