### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by shmuel-krakower** [yahoo/gifshot#43]
While video is captured from the camera I'd like the user to be able to see what's being captured.
It would also be nice to allow showing the camera input before the user initiate the actual capture.

Any idea how this could be achieved?

**Comment by vettorazi** [comment]
i miss that too. so i just created a canvas with the live view of the webcam in other div.
with a little hack you can hide and show when need.
`
<script>
// Put event listeners into place
window.addEventListener("DOMContentLoaded", function() {
	// Grab elements, create settings, etc.
	var canvas = document.getElementById("canvas"),
		context = canvas.getContext("2d"),
		video = document.getElementById("video"),
		videoObj = { "video": true },
		errBack = function(error) {
			console.log("Video capture error: ", error.code);
		};

	// Put video listeners into place
	if(navigator.getUserMedia) { // Standard
		navigator.getUserMedia(videoObj, function(stream) {
			video.src = stream;
			video.play();
		}, errBack);
	} else if(navigator.webkitGetUserMedia) { // WebKit-prefixed
		navigator.webkitGetUserMedia(videoObj, function(stream){
			video.src = window.webkitURL.createObjectURL(stream);
			video.play();
		}, errBack);
	}
	else if(navigator.mozGetUserMedia) { // Firefox-prefixed
		navigator.mozGetUserMedia(videoObj, function(stream){
			video.src = window.URL.createObjectURL(stream);
			video.play();
		}, errBack);
	}
}, false);
</script>`

in the html:

`      <video id="video" width="640" height="480" autoplay></video>
<button id="createGIFButton">Snap Photo</button>
<canvas id="canvas" width="640" height="480"></canvas>
`
