### ISSUE TITLE
numframe bug

### ISSUE THREAD

**Issue by pfloyd555** [yahoo/gifshot#45]
I am using yahoo gifshot library to create gifs from videos. A user can upload a video and, afterwards, I dynamically create a gif from that video. The problem is, that user uploads a two-second duration video but the gif is only saved as one second duration...
here is code :

gifshot.createGIF({
                'video': [U + 'Content/convertedVideos/bla.mp4'],
                'gifWidth': 800,
                'gifHeight': 400,
                ...

i've added numframes property which works fine but another problem is it repeats both first shows one second duration gif and after two second gif

'video': [U + 'Content/convertedVideos/bla.mp4],
            'gifWidth': 800,
            'gifHeight': 400,
            'numFrames': 20,

how can i save only two second duration gif?
see also stackoverflow : http://stackoverflow.com/questions/33500785/yahoo-gifshot-javascript-numframe-bug

**Comment by wgottschalk** [comment]
I'm having a similar problem. I'm building a chrome extension to create GIFs from the HTML5 video element. The videos will save if they are 1 sec but will not save for any time over that amount.

**Comment by nguyentk90** [comment]
@wgottschalk The default of numFrames is 10 that means the length of GIF created would be 1s. As document mention **Each frame is captured every 100 milleseconds of a video**. So if you want to keep the length of your video same with your GIF you should set the numFrames with new value, **numFrames = (videoDuration * 1000) / 100**.
@pfloyd555 For your case, you should reduce the numFrames 1 or 2 frames. In theory, numFrames of 2s video duration must be 20, but in real world, it should be removed 2 frames. I also answered your question on [stackoverflow](http://stackoverflow.com/a/35006883/1888929).

**Comment by gfranko** [comment]
Nice answer, @nguyentk90
