### ISSUE TITLE
Use base64 on images attribute

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [yahoo/gifshot#47]
Can I send an array of base64 photos into `images` attribute?

**Comment by siddharthnaik7** [comment]
Hi @caio-ribeiro-pereira , have you got the answer.. I am looking for the same.

**Comment by caio-ribeiro-pereira** [comment]
Well, I don't remenber @siddharthnaik7 almost 2 years in this opened issue, time pass! hahaha

**Comment by siddharthnaik7** [comment]
ohh ok, no worries, I will try to find it, Thanks :)

**Comment by caio-ribeiro-pereira** [comment]
@siddharthnaik7 you're welcome! :D

**Comment by rrundle** [comment]
@siddharthnaik7 did you ever find an answer to this? I'm sending an array but getting an error back.

**Comment by dugagjinll** [comment]
@rrundle 
it works _partially_ for me. 
Transparency turns black colored. :(

The code: 
```
    gifshot.createGIF({
            gifWidth: 500,
            gifHeight: 500,
            images: base64images,
            interval: 1,
            numWorkers: 4
        },
        function(obj) {
            if (!obj.error) {
                $('#divToAppend').append(
                    '<div class="imgContainer col s12 m12 l12">' +
                        '<img class="" src="' + obj.image + '" />' +
                    '</div>'
                );
            }
        });
```

where **base64images** variable is just an array where each element is a base64 encoded image (data:image/png;base64,iVBORw0K...).

**Comment by dugagjinll** [comment]
I found a way to solve my problem where transparency turns black. 

The solution is that you have to generate a non-transparent image on the fly and put it as the first element in the array. 

In my case, I generated a 500x500 white (RGB = 255, 255, 255) base64 encoded image.
Then I added it as first element of my base64images array:

    const whiteBase64Image = "data:image/png:base64,iVBORw0K...";
    base64images.unshift(whiteBase64Image);

My final code becomes: 

    const whiteBase64Image = "data:image/png:base64,iVBORw0K...";
    base64images.unshift(whiteBase64Image);
    gifshot.createGIF({
            gifWidth: 500,
            gifHeight: 500,
            images: base64images,
            interval: 0.05
        },
        function(obj) {
            if (!obj.error) {
                $('#divToAppend').append(
                    '<div class="imgContainer col s12 m12 l12">' +
                        '<img class="" src="' + obj.image + '" />' +
                    '</div>'
                );
            }
        });

It's maybe an ugly way to do it but since my interval is low, this does the job.
