### ISSUE TITLE
Gif not animating on Chrome/44.0.2403.157 Crosswalk/15.44.384.13

### ISSUE THREAD

**Issue by Titoine** [yahoo/gifshot#50]
Hi,
first, thanks for this awesome lib!

But I got a problem in my Cordova app with the plugin Crosswalk. Generated GIF doesn't launch (first frame but nothing else).
I'm doing the same thing on my desktop Chrome and It's working perfectly.
The result is :
- On desktop :  image: "data:image/gif;base64,R0lGODlhyADIAAAAACH/C05FVFND…8uhQjjSb6RIWxk852LQAz4At40wv+GzsUcBgH0AHfFhAAOw=="
- On Crosswalk : image: "data:image/gif;base64,R0lGODlhyADIAAAAACH/C05FVFND…aARFqoRYlhwNlkA7XYAxiUAMp9oUqwJsR8ACJTQRWcAUBAQA7"

As you see the start is that same but ending is different.
The desktop gif work on both platform.

Any idea ?

**Comment by snowbreeze** [comment]
I get only a single image not the whole animation in crosswalk

**Comment by gfranko** [comment]
You should be able to manipulate the `image` string that gifshot sends back to you in the callback function (change it based on platform)
