### ISSUE TITLE
How can set start time for video when creating GIF?

### ISSUE THREAD

**Issue by nguyentk90** [yahoo/gifshot#51]
Thanks for awesome library ;).

I'm trying it. I think about how I can set start time for video when creating GIF. For example, my video have duration 20s and I want to create GIF from second 10 to second 20.

Any solution help me achieve it?

Thanks.

**Comment by livegothub2015** [comment]
How do u suck my dick

**Comment by dreday966** [comment]
I also need this functionality

**Comment by wwpearce** [comment]
+1

**Comment by gfranko** [comment]
Not yet, PR's are welcome (although I would wait a day or two until our new ES6 release is out)
