### ISSUE TITLE
Posibility to Post data to image Links?

### ISSUE THREAD

**Issue by Tobias-De** [yahoo/gifshot#54]
HI, 
currently i fill gifshot with images. 
These Image url look like so "/generate.php?time=123456"
That works fine, however i need an additional data array to Post to that php page.
Is that with Gifshot possible? Currently the only way is to put an array with Links.
For me its not possible to put that additional information to the Link because of Length limitation of 2000 characters of an url.
i imagine something of the following:

```
 var arr = new Array();
arr [0]="123";
arr [1]="345";
.... 

var urls = new Array();
urls[0]="generate.php?time=7945641";
urls[1]="generate.php?time=4562167";
....

gifshot.createGIF({'gifWidth': 1000,'gifHeight': 1000,'interval': 1.5,
    'images': urls, 'postData': arr 
},function(obj) {
    if(!obj.error) {
        var image = obj.image,
        animatedImage = document.createElement('img');
        animatedImage.src = image;

        var myNode = document.getElementById("result");
        while (myNode.firstChild) {
            myNode.removeChild(myNode.firstChild);
        }

       myNode.appendChild(animatedImage);
    }
});
```

**Comment by gfranko** [comment]
We won't be supporting this unfortunately
