### ISSUE TITLE
Rotated Frames on iOS MOV file

### ISSUE THREAD

**Issue by snowbreeze** [yahoo/gifshot#58]
![download](https://cloud.githubusercontent.com/assets/8898721/14844235/872caba2-0c73-11e6-9f9f-5cc4b91066b7.gif)

I am using a video uri, captured using the capture plugin. Then passing the  video. Its a .MOV video.
The internal video element is fine too. I made its opacity 1.

**Comment by snowbreeze** [comment]
This is safari specific. On chrome it works correctly. In safari thought the html5 video element displays correctly, it probalby doesnt render to canvas correctly. Still I wonder how the first image is correctly oriented.

**Comment by snowbreeze** [comment]
Note safari works correctly with mp4 files. Looks like Safari + .mov recorded on ios = the above

**Comment by cooljeffro** [comment]
I was seeing this same issue on iOS.  It looks like the frames are getting distorted before they are passed into the gifshot library, so this is probably an iOS bug.  Have you found any workaround for this?

**Comment by snowbreeze** [comment]
No I had to dump the project. I moved to native. Lots of issues.

**Comment by gfranko** [comment]
The existing video on the site works... try the latest version of gifshot that we just released
