### ISSUE TITLE
Losing transparency from png to gif

### ISSUE THREAD

**Issue by ranbuch** [yahoo/gifshot#66]
gifshot["createGIF"]({images: pngImagesWithTransparency}, function (obj) {
//success but the gif has a background :(
});

Any idea how to fix it?

Thx

**Comment by gfranko** [comment]
Can you set up a demo page for us to look at?

**Comment by gfranko** [comment]
Closing this for now

**Comment by tsunamilx** [comment]
Hi same issue here:

![image](https://user-images.githubusercontent.com/6290337/30241075-57df6d28-95af-11e7-9337-195a1c76b2a0.png)

My code:

```javascript
    var images = [];
    // Source PNGs with same size and transparency.
    for (var i = 0; i < 11; i ++) {
      images.push('pngs/' + i + '.png');
    }
    gifshot.createGIF({
      images: images,
      gifWidth: 900,
      gifHeight: 900,
      interval: 0.2,
    }, function (obj) {
      if (! obj.error) {
        document.querySelector('.result').src = obj.image;
      }
    });
```
