### ISSUE TITLE
Can't make GIF from existing stream

### ISSUE THREAD

**Issue by davidgilbertson** [yahoo/gifshot#68]
I'm new to all this so I hope I'm just missing something obvious.

I am trying to get an animated gif from a desktop recording, rather than a webcam. I can get the stream no problem, I can get it into a video or canvas element just fine, but I can't work out how to get it into gifshot.

Can I override the object that gifshot passes in to `getUserMedia` to specify I want the desktop, not a webcam, or will that always just be [`video: true`](https://github.com/yahoo/gifshot/blob/c1a36b26fa7bbf0200f906d156297874a284e9e8/src/modules/core/videoStream.js#L151)?

The object I want to pass to `getUserMedia` is this:

``` js
{
  audio: false,
  video: {
    mandatory: {
      chromeMediaSource: 'desktop',
      chromeMediaSourceId: sourceId
    }
  }
}
```

If I get the stream myself and assign it to a video element like `videoEl.src = URL.createObjectURL(stream);` and pass that video element to gifshot, gifshot [checks the extension](https://github.com/yahoo/gifshot/blob/c1a36b26fa7bbf0200f906d156297874a284e9e8/src/modules/core/existingVideo.js#L35) and says the codec isn't supported (edit, although I think this might be a rookie mistake on my part since it's a stream).

FYI this is all inside electron, I don't know if that makes a difference.

**Comment by gfranko** [comment]
We will support passing blob urls in the `video` option in the new release
