### ISSUE TITLE
Simple images to gif demo not working.Why ?

### ISSUE THREAD

**Issue by mburakerman** [yahoo/gifshot#71]
I created simple demo on Jsfiddle but the code not creating gif from images.Why?
[Jsfiddle](https://jsfiddle.net/1kmndyyy/)
```
gifshot.createGIF({
  images: [
    'https://www.daysoftheyear.com/wp-content/images/bird-day-1-e1450957454568-808x380.jpg',
    'https://files.allaboutbirds.net/wp-content/themes/html5blank-stable/images/blue-winged-warbler.jpg',
    'http://feelgrafix.com/data_images/out/28/980143-bird.jpg'
  ]
}, function(obj) {
  if (!obj.error) {
    var image = obj.image,
      animatedImage = document.createElement('img');
    animatedImage.src = image;
    document.body.appendChild(animatedImage);
  }
});
```

**Comment by PatMattei** [comment]
Some of the images you're trying to load come from sites that don't allow sharing in this way (take out the lats two images and it works).  Try hosting the images and code on your own site.  I'm getting the following error when I try to run your code:

> Image from origin 'http://feelgrafix.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://fiddle.jshell.net' is therefore not allowed access.

**Comment by mburakerman** [comment]
Ah , i see. I am also getting the same error. Tried hosting the images another website and it worked!
Thanks!
