### ISSUE TITLE
is this supported in iOS web view?

### ISSUE THREAD

**Issue by pliablepixels** [yahoo/gifshot#77]
Hi there,
thanks for this library. I was able to successfully use it in Android and Desktop, but can't get it to work in IOS

`gifshot.isExistingImagesGIFSupported()` returns true
I don't need webcam support, but just  gifShot.Create for images.

My invocation:

```
gifshot.createGIF(
                    {
                        'images': img, //array of images
                        'gifWidth': ad.w,
                        'gifHeight': ad.h,
                        //'images': imgs,
                        'text': 'hello',
                    }, function(obj) {}
```

It never enters function(obj)

**Comment by pliablepixels** [comment]
After further investigation, it looks like it seems to be struggling if the images are of this format
```
https://server:port/zm/index.php?view=image&path=1/16/11/18/18/23/21/00290-capture.jpg
```

This URL actually returns an image and works fine in both Android and Desktop. But not iOS

**Comment by pliablepixels** [comment]
Problem solved!
I had to use
```
crossOrigin': 'use-credentials',
```

**Comment by tetreault** [comment]
Have you tested this with video on iOS? Am using iOS 11. @pliablepixels @gfranko 

Runs fine on desktop, on mobile safari I get: 

```
Unhandled Promise Rejection: NotAllowedError (DOM Exception 35): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```

and it points to `stream` and `startStreaming`.

**Comment by pliablepixels** [comment]
@tetreault , the solution I finally adopted was based on omggif which I believe gif shot also uses. The very talented @jimmywarting helped me and implemented/adapted it to work with his StreamSaver library. Bottom line, I am using it successfully to write animated GIFs. I am on IOS 11, works fine

https://github.com/jimmywarting/StreamSaver.js/issues/38

**Comment by tetreault** [comment]
Thanks for the reply @pliablepixels. I was tired and not paying attention yesterday and it was my own stupid mistake! Running GIFShot on page load was great for my browser tests but obviously was failing on mobile because it requires that explicit gesture to run the library since its running `video.play` under the hood. Now that I put gifshot inside a click handler its fine on mobile.
