### ISSUE TITLE
camera isn't release on chromium or chrome on linux/ubuntu

### ISSUE THREAD

**Issue by silky** [yahoo/gifshot#82]
i don't know why

it _is_ released in firefox.

**Comment by GaelCoat** [comment]
`stopVideoStreaming()` uses a deprecated function on chrome/firefox (maybe Opera)
[https://developers.google.com/web/updates/2015/07/mediastream-deprecations](https://developers.google.com/web/updates/2015/07/mediastream-deprecations)

on chrome/firefox it should be -> `cameraStream.getVideoTracks()[0].stop()`
and `cameraStream.stop()` for IE/etc...

Hope this help.

**Comment by silky** [comment]
it does help! thanks! :)
