### ISSUE TITLE
Returned error when sending image array to createGIF

### ISSUE THREAD

**Issue by rrundle** [yahoo/gifshot#84]
Here's my code: 

  ` gifshot.createGIF({images: array}, function(obj) {
            if(!obj.error) {
                var image = obj.image;
                return callback(image);
            }
            else {
                console.log('error from gifshot!')
            }
        });
`

where array is an array of base64 images. 

Any ideas what the issue might be?

**Comment by stevenfabre** [comment]
I have a similar issue. Tried to use blog urls instead but I get the same error in the console:
<img width="791" alt="screen shot 2017-05-08 at 9 36 26 pm" src="https://cloud.githubusercontent.com/assets/2289736/25802625/73182d6c-3436-11e7-8c20-deceb128abe4.png">

**Comment by gfranko** [comment]
Can you try again? We just released a new version of gifshot.
