### ISSUE TITLE
video.play() Error: only user gesture can trigger .play()

### ISSUE THREAD

**Issue by freddi301** [yahoo/gifshot#86]
Recently browsers forbid to call video.play() programmatically, so we cannot encode anymore existing videos to gifs :cry:

**Comment by gfranko** [comment]
Still seems to work for me in both Chrome and Firefox... which browsers are you talking about?

**Comment by freddi301** [comment]
Safari, latest Chrome and Firefox

**Comment by gfranko** [comment]
I just updated to the latest Chrome, and everything seems to be working fine without a hitch.
