### ISSUE TITLE
Add option to create a GIF starting from a start time

### ISSUE THREAD

**Issue by cranberryofdoom** [yahoo/gifshot#93]
Hi, awesome job on the library so far! The API is clear and straightforward and I really appreciate that.

I was wondering whether it was on the roadmap of feature improvements to specify a start time for frame capture when creating a GIF from a video. If not, I was thinking of forking it and making a PR to do just that-- we're trying to prototype creating multiple GIFs from an uploaded video to allow our users to choose the one they like-- so we need to capture the frames of the GIF starting at a specific time.

Let me know! 😄

**Comment by gfranko** [comment]
#94
